import forms from "@tailwindcss/forms";

export default {
    content: ["./resources/**/*.blade.php", "./resources/**/*.js"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-high": "#e7e8f0",
                "secondary-fixed": "#8ef4e9",
                "primary-fixed-dim": "#a8c8ff",
                "inverse-primary": "#a8c8ff",
                "surface-bright": "#f9f9ff",
                "surface-variant": "#e1e2ea",
                "secondary-container": "#8bf1e6",
                "tertiary-container": "#4c636e",
                "on-primary-fixed": "#001b3d",
                "inverse-surface": "#2e3036",
                surface: "#f9f9ff",
                "on-secondary": "#ffffff",
                primary: "#00488d",
                background: "#f9f9ff",
                "on-background": "#191c21",
                "primary-fixed": "#d6e3ff",
                tertiary: "#344b56",
                "on-surface-variant": "#424752",
                "secondary-fixed-dim": "#71d7cd",
                outline: "#727783",
                "inverse-on-surface": "#eff0f8",
                "tertiary-fixed": "#cde6f4",
                "surface-container": "#ecedf6",
                "surface-container-highest": "#e1e2ea",
                "on-error": "#ffffff",
                "on-secondary-fixed-variant": "#00504a",
                "on-surface": "#191c21",
                error: "#ba1a1a",
                "on-tertiary": "#ffffff",
                "on-primary-fixed-variant": "#00468b",
                "surface-tint": "#005db5",
                "on-primary-container": "#cadcff",
                "tertiary-fixed-dim": "#b1cad7",
                "surface-container-low": "#f2f3fb",
                "surface-dim": "#d8dae2",
                "on-tertiary-container": "#c5deec",
                "on-tertiary-fixed": "#051e28",
                "on-tertiary-fixed-variant": "#334a55",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "outline-variant": "#c2c6d4",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed": "#00201d",
                secondary: "#006a63",
                "primary-container": "#005fb8",
                "on-secondary-container": "#006f67",
                "on-primary": "#ffffff",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            fontFamily: {
                headline: ["Manrope"],
                body: ["Inter"],
                label: ["Inter"],
            },
        },
    },
    plugins: [forms],
};
